
#include "./linear_root"
#include "./linear_solver"
#include "./quadratic_roots"
#include "./quadratic_solver"
#include "./cubic_roots"
#include "./cubic_solver"
#include "./quartic_roots"
#include "./quartic_solver"
#include "./is_quadratic_solvable"
#include "./is_cubic_solvable"
#include "./is_quartic_solvable"
#include "./is_quintic_solvable"
// #include "./linsolve"
