
#include "./linear_root"
#include "./quadratic_roots"
#include "./cubic_roots"
#include "./quartic_roots"
#include "./degenerate_roots"
#include "./poly_roots"
#include "./bisection_root"
#include "./neubauer_root"
#include "./newton_bisection_root"
#include "./newton_neubauer_root"
#include "./is_quadratic_solvable"
#include "./is_cubic_solvable"
#include "./is_quartic_solvable"
#include "./is_quintic_solvable"
#include "./test_cubic"
#include "./test_quartic"
