#include "./uniforms_volume"
#include "./uniforms_textures"
#include "./uniforms_color_map"
#include "./uniforms_rendering"
#include "./uniforms_shading"
#include "./uniforms_lighting"
#include "./uniforms_debugging"
